name: smart_sizer
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


