name: smart_sizer
description: "A set of Flutterfor measuring screens and automatic responsiveness with all systems and screens.."
version: 1.0.3
# homepage:
repository: https://github.com/Ah95ed/smart_size
environment:
  sdk: ^3.8.1
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


